### ISSUE TITLE
Workflow results

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/compute-service-api#2]
According to the CWL spec, workflows can end in either success, temporaryFailure, or permanentFailure. We now have Waiting, Running, Success, Canceled, TemporaryFailure, Failed, and SystemError. Those should be reconciled somehow.

**Comment by LourensVeen** [comment]
I think we need to know what these things really mean first. It seems that there are four things here: the state of the workflow execution, the result of the workflow execution, the reason for failure, and whether it makes sense to retry the job unchanged:

State
- Waiting
- Running
- (Finished)

Result
- Success
- Failed

Reason
- Canceled
- SystemError
- (WorkflowError)

Run again
- SystemError
- TemporaryFailure
- PermanentFailure

CWL specifies that permanentFailure is returned for e.g. invalid expressions in the workflow document. How to interpret the return value of a command line tool can be specified by the creator of the workflow. So I think if we're using CWL for the workflows, then we need at least Success, PermanentFailure and TemporaryFailure as possibilities, otherwise we'd be incompatible with some workflows. If the job ends due to some external circumstance, then we can have additional error messages. And we'd like to combine things into a single list.

So that leads to
- Waiting
- Running
- Finished
  - Success
  - Failed
    - Canceled (don't run again, probably)
    - SystemError (run again)
    - CWL TemporaryFailure (run again)
    - CWL PermanentFailure (don't run again)

Which can then be simplified to
- Waiting (job in queue, VM suspended, etc.)
- Running
- Success (completed, system worked fine, CWL status success)
- Canceled (due to user action, no CWL result)
- SystemError (compute resource on fire, no CWL result)
- TemporaryFailure (system worked fine, CWL status temporaryFailure)
- PermanentFailure (system worked fine, CWL status permanentFailure)

So I propose replacing Failure with PermanentFailure, and using the above semantics to determine when to return what.

**Comment by LourensVeen** [comment]
Oh by the way, Cancelled with double-l seems to be the common spelling :-).

**Comment by LourensVeen** [comment]
Slightly better meanings:
- Waiting (job in queue, VM suspended, etc.)
- Running
- Success (completed, system worked fine, CWL status success, output available)
- Cancelled (due to user action, no CWL status, no output)
- SystemError (compute resource on fire, no CWL status, no output)
- TemporaryFailure (system worked fine, CWL status temporaryFailure, no output)
- PermanentFailure (system worked fine, CWL status permanentFailure, no output)

How's this?

**Comment by nielsdrost** [comment]
Fixed with fc531a74a04f7a8943079b9ffcb1454c9b01ac1e
